name: "Foss Scanner"
description: "Check your application for foss vulnerabilties"
branding:
  icon: "cloud-snow"
  color: "blue"
runs:
  using: "docker"
  image: "docker://saurabhthatte/foss-scan:v2"
